apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rhodges-redis-data
  labels:
    env: test
    username: rhodges
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi