apiVersion: v1
kind: Service
metadata:
  name: rhodges-test-redis-service
  labels:
    env: test
    username: rhodges
spec:
  type: ClusterIP
  selector:
    app: rhodges-test-redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379