apiVersion: v1
kind: Service
metadata:
  name: rhodges-test-flask-service
  labels:
    env: test
    username: rhodges
spec:
  type: ClusterIP
  selector:
    app: rhodges-test-flask
  ports:
  - name: flask
    port: 5000
    targetPort: 5000